"""
dSPACE CAN Bus API constants — translated from DSBusApiCanItfs.h

Reference: dSPACE Bus API Manual, CAN API Reference (pp. 53-57, 75-76, 106-108, 137-140)
"""

import ctypes

# ---------- General constants ----------
DSCAN_MAX_DATA_LENGTH = 64
DSCAN_MAX_NAME_LENGTH = 256
DSCAN_INVALID_CAN_HANDLE = -1
DSCAN_INVALID_EVENT_HANDLE = 0
DSCAN_MAX_TEXT_LENGTH = 2048
DSCAN_MAX_RX_QUEUE_SIZE = 32768
DSCAN_CRYSTAL_FREQUENCY_SJA1000 = 16_000_000
DSCAN_CLOCK_FREQUENCY_SJA1000 = DSCAN_CRYSTAL_FREQUENCY_SJA1000 // 2
DSCAN_INVALID_TIME_VAL = -1

# ---------- Vendor names ----------
DSCAN_VENDOR_NAME_UNKNOWN = "Unknown vendor"
DSCAN_VENDOR_NAME_DSPACE = "dSPACE"
DSCAN_VENDOR_NAME_EBERSPAECHER = "Eberspaecher"
DSCAN_VENDOR_NAME_KVASER = "Kvaser"
DSCAN_VENDOR_NAME_PEAK = "PEAK-System"
DSCAN_VENDOR_NAME_VECTOR = "Vector Informatik"

# ---------- Interface names ----------
DSCAN_INTERFACE_NAME_UNKNOWN = "Unknown interface"
DSCAN_INTERFACE_NAME_DSPACE_DCI_CAN2 = "DCI-CAN2"
DSCAN_INTERFACE_NAME_DSPACE_DCI_CANLIN1 = "DCI-CAN/LIN1"
DSCAN_INTERFACE_NAME_KVASER_LEAF = "Leaf"
DSCAN_INTERFACE_NAME_KVASER_MEMORATOR_PRO = "Memorator Professional"
DSCAN_INTERFACE_NAME_KVASER_USB_CAN_II = "USBcan II"
DSCAN_INTERFACE_NAME_KVASER_USB_CAN_PRO = "USBcan Professional"
DSCAN_INTERFACE_NAME_PEAK_PCAN_MINI_PCIE_FD = "PCAN-miniPCIe FD"
DSCAN_INTERFACE_NAME_VECTOR_CANCASE_XL = "CANcaseXL"
DSCAN_INTERFACE_NAME_VECTOR_VN1610 = "VN1610"
DSCAN_INTERFACE_NAME_VECTOR_VN1611 = "VN1611"
DSCAN_INTERFACE_NAME_VECTOR_VN1630 = "VN1630"
DSCAN_INTERFACE_NAME_VECTOR_VN1640 = "VN1640"
DSCAN_INTERFACE_NAME_VECTOR_VN5610 = "VN5610"
DSCAN_INTERFACE_NAME_VECTOR_VN5610A = "VN5610A"
DSCAN_INTERFACE_NAME_VECTOR_VN7600 = "VN7600"
DSCAN_INTERFACE_NAME_VECTOR_VN8900 = "VN8900"
DSCAN_INTERFACE_NAME_VIRTUAL = "Virtual"

# ---------- Bus types ----------
DSCAN_INTERFACE_BUS_TYPE_UNKNOWN = "Unknown bus"
DSCAN_INTERFACE_BUS_TYPE_VIRTUAL = "Virtual"
DSCAN_INTERFACE_BUS_TYPE_USB = "USB"
DSCAN_INTERFACE_BUS_TYPE_PCMCIA = "PCMCIA"
DSCAN_INTERFACE_BUS_TYPE_PCI_EXPRESS = "PCI Express"
DSCAN_INTERFACE_BUS_TYPE_ETHERNET = "Ethernet"

# ---------- Channel capabilities (bitmask) ----------
DSCAN_CHANNEL_CAPABILITY_FD = 0x00000001
DSCAN_CHANNEL_CAPABILITY_FIXED_CONTROLLER_CONFIGURATION = 0x00000002
DSCAN_CHANNEL_CAPABILITY_BUS_LOAD_INFO = 0x00000004
DSCAN_CHANNEL_CAPABILITY_FD_NON_ISO = 0x00000008
DSCAN_CHANNEL_CAPABILITY_BUS_STATISTICS = 0x00000010
DSCAN_CHANNEL_CAPABILITY_TX_TIMESTAMP_SYNC = 0x00000020
DSCAN_CHANNEL_CAPABILITY_HIGH_SPEED_CONNECTION = 0x00000100

# ---------- Enumerations ----------
# DSECanChannelsSearchAttributeType
DSCAN_SEARCH_ATTRIBUTE_TYPE_IP_V4_ADDRESS = 1

# DSECanIdentifierType
DSCAN_IDENTIFIER_TYPE_STD = 0x01       # 11-bit standard identifiers only
DSCAN_IDENTIFIER_TYPE_XTD = 0x02       # 29-bit extended identifiers only
DSCAN_IDENTIFIER_TYPE_STD_XTD = 0x03   # both standard and extended

# DSECanMessageType
DSCAN_MESSAGE_TYPE_DATA = 1
DSCAN_MESSAGE_TYPE_REMOTE = 2
DSCAN_MESSAGE_TYPE_ERROR = 3
DSCAN_MESSAGE_TYPE_BUS_INFO = 4
DSCAN_MESSAGE_TYPE_BUS_STATISTICS = 5

# DSECanBusStatus
DSCAN_BUS_STATUS_UNKNOWN = 0
DSCAN_BUS_STATUS_ACTIVE = 1
DSCAN_BUS_STATUS_PASSIVE = 2
DSCAN_BUS_STATUS_WARNING = 3
DSCAN_BUS_STATUS_BUS_OFF = 4

# DSECanChannelOutputMode
DSCAN_CHANNEL_OUTPUT_NORMAL = 0
DSCAN_CHANNEL_OUTPUT_SILENT = 1
DSCAN_CHANNEL_OUTPUT_DISCONNECT = 2

# ---------- CAN baud rates (bit/s) ----------
DSCAN_BAUD_1M = 1_000_000
DSCAN_BAUD_800K = 800_000
DSCAN_BAUD_500K = 500_000
DSCAN_BAUD_250K = 250_000
DSCAN_BAUD_125K = 125_000
DSCAN_BAUD_100K = 100_000
DSCAN_BAUD_50K = 50_000
DSCAN_BAUD_20K = 20_000
DSCAN_BAUD_10K = 10_000

# CAN FD data baud rates (bit/s)
DSCAN_BAUD_FD_2M = 2_000_000
DSCAN_BAUD_FD_5M = 5_000_000
DSCAN_BAUD_FD_8M = 8_000_000

# ---------- CAN FD DLC ↔ byte count mapping ----------
# DLC 0-8 map 1:1; DLC 9-15 are non-linear (CAN FD only)
_DLC_TO_BYTES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 16, 20, 24, 32, 48, 64]
_BYTES_TO_DLC = {v: i for i, v in enumerate(_DLC_TO_BYTES)}

def dlc_to_byte_count(dlc: int) -> int:
    """Convert DLC (0-15) to actual data byte count."""
    return _DLC_TO_BYTES[dlc] if 0 <= dlc <= 15 else 0

def byte_count_to_dlc(byte_count: int) -> int:
    """Convert data byte count to the smallest DLC that fits."""
    for dlc, size in enumerate(_DLC_TO_BYTES):
        if byte_count <= size:
            return dlc
    return 15

# ---------- CAN acceptance ----------
DSCAN_ACCEPTANCE_ALL = 0x00000000  # accept all messages
DSCAN_ACCEPTANCE_NONE = 0xFFFFFFFF  # reject all messages

# ---------- TX flags (ulFlags in DSSCanMessage for DSCAN_TransmitMessages) ----------
DSCAN_TX_MESSAGE_FLAG_FD = 0x00000001             # transmit CAN FD message
DSCAN_TX_MESSAGE_FLAG_FD_BAUDRATE_SWITCH = 0x00000002  # CAN FD with baud rate switch

# ---------- RX flags (ulFlags in DSSCanMessage for DSCAN_ReadReceiveQueue) ----------
DSCAN_RX_MESSAGE_FLAG_TX_ACKNOWLEDGE = 0x00000001       # transmitted by same handle
DSCAN_RX_MESSAGE_FLAG_CTRL_TX_LOOPBACK = 0x00000002     # transmitted by same controller
DSCAN_RX_MESSAGE_FLAG_FD = 0x00000100                   # CAN FD message
DSCAN_RX_MESSAGE_FLAG_FD_BAUDRATE_SWITCH = 0x00000200   # CAN FD with baud rate switch
DSCAN_RX_MESSAGE_FLAG_RX_BUFFER_OVERRUN = 0x00010000    # vendor API buffer overrun
DSCAN_RX_MESSAGE_FLAG_HW_RX_BUFFER_OVERRUN = 0x00020000 # CAN controller buffer overrun
DSCAN_RX_MESSAGE_FLAG_FD_ERROR_STATE_INDICATOR = 0x00040000  # CAN FD ESI

# ---------- Error codes ----------
DSCAN_ERR_NO_ERROR = 0
DSCAN_ERR_GENERAL = -1
DSCAN_ERR_NOT_INITIALIZED = -2
DSCAN_ERR_INVALID_HANDLE = -3
DSCAN_ERR_INVALID_PARAMETER = -4
DSCAN_ERR_CHANNEL_NOT_AVAILABLE = -5
DSCAN_ERR_CHANNEL_ALREADY_REGISTERED = -6
DSCAN_ERR_CHANNEL_NOT_REGISTERED = -7
DSCAN_ERR_CHANNEL_ALREADY_ACTIVATED = -8
DSCAN_ERR_CHANNEL_NOT_ACTIVATED = -9
DSCAN_ERR_CHANNEL_DEACTIVATED = -10
DSCAN_ERR_OUT_OF_MEMORY = -11
DSCAN_ERR_QUEUE_EMPTY = -12
DSCAN_ERR_QUEUE_OVERRUN = -13
DSCAN_ERR_TIMEOUT = -14
DSCAN_ERR_NOT_SUPPORTED = -15
DSCAN_ERR_VENDOR_SPECIFIC = -16
DSCAN_ERR_NO_LICENSE = -17
DSCAN_ERR_ACCESS_DENIED = -18
DSCAN_ERR_DEPRECATED = -19
DSCAN_ERR_CHANNEL_OUTPUT_SILENT = -20
DSCAN_ERR_CHANNEL_OUTPUT_DISCONNECT = -21

ERROR_TEXT = {
    DSCAN_ERR_NO_ERROR: "No error",
    DSCAN_ERR_GENERAL: "General error",
    DSCAN_ERR_NOT_INITIALIZED: "Not initialized",
    DSCAN_ERR_INVALID_HANDLE: "Invalid handle",
    DSCAN_ERR_INVALID_PARAMETER: "Invalid parameter",
    DSCAN_ERR_CHANNEL_NOT_AVAILABLE: "Channel not available",
    DSCAN_ERR_CHANNEL_ALREADY_REGISTERED: "Channel already registered",
    DSCAN_ERR_CHANNEL_NOT_REGISTERED: "Channel not registered",
    DSCAN_ERR_CHANNEL_ALREADY_ACTIVATED: "Channel already activated",
    DSCAN_ERR_CHANNEL_NOT_ACTIVATED: "Channel not activated",
    DSCAN_ERR_CHANNEL_DEACTIVATED: "Channel deactivated",
    DSCAN_ERR_OUT_OF_MEMORY: "Out of memory",
    DSCAN_ERR_QUEUE_EMPTY: "Queue empty",
    DSCAN_ERR_QUEUE_OVERRUN: "Queue overrun",
    DSCAN_ERR_TIMEOUT: "Timeout",
    DSCAN_ERR_NOT_SUPPORTED: "Not supported",
    DSCAN_ERR_VENDOR_SPECIFIC: "Vendor-specific error",
    DSCAN_ERR_NO_LICENSE: "No license",
    DSCAN_ERR_ACCESS_DENIED: "Access denied",
    DSCAN_ERR_DEPRECATED: "Deprecated",
    DSCAN_ERR_CHANNEL_OUTPUT_SILENT: "Channel output silent",
    DSCAN_ERR_CHANNEL_OUTPUT_DISCONNECT: "Channel output disconnected",
}
